export {AuthModule} from './auth/auth.module'
export {AppHomeModule} from './app-home/app-home.module'
export {AccountModule} from './account/account.module'
export {SettingsModule} from './settings/settings.module'
export {PermissionCentreModule} from './permission-centre/permission-centre.module'