export const CHANGE_PASSWORD: string = "change-password"
export const CREATE_NEW_PROFILE: string = "create-new-profile"
export const GET_PROFILES: string = "get-profiles"
export const SEND_VERIFICATION_CODE: string = "send-verification-code"
export const VERIFY_PROFILE: string = "verify-profile"
export const DELETE_PROFILE: string = "delete-profile"